version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    ignore:
      - dependency-name: "k8s.io/*"
      - dependency-name: "github.com/docker/docker"
    labels:
    - bot/dependency

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: auto
    labels:
    - bot/dependency
