# https://taskfile.dev

version: '3'

tasks:
  prepare:
    desc: Prepare the environment
    cmds:
      - echo "Preparing the environment"

  build_server:
    desc: Build the server
    cmds:
      - echo "Building the server {{.GOOS}} {{.GOARCH}}"

  package_gui:
    desc: Package the GUI
    cmds:
      - echo "Packaging the GUI for {{.GOOS}} {{.GOARCH}}"

  build_cli:
    desc: Build the CLI
    cmds:
      - echo "Packaging the GUI for {{.GOOS}} {{.GOARCH}}"

  default:
    cmds:
      - task: prepare
      - task: build_server
        vars: {
          GOOS: darwin,
          GOARCH: arm64
        }
